version: 2
updates:
  # Maintain dependencies for python
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "django-filter"
        versions: ["*"]
    groups:
      python-version-updates:
        applies-to: "version-updates"
        patterns: ["*"]
      python-security-updates:
        applies-to: "security-updates"
        patterns: ["*"]

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/ccm_web/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      npm-version-updates:
        applies-to: "version-updates"
        patterns: ["*"]
      npm-security-updates:
        applies-to: "security-updates"
        patterns: ["*"]
