[supervisord]
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes=0
loglevel=info
pidfile=/tmp/supervisord.pid

[program:backend]
command=bash -c ./shell_scripts/start.sh
directory=/code
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=10
startsecs=5
startretries=2

[program:frontend]
command=bash -c "if [ \"$RUN_FRONTEND\" = \"true\" ]; then echo 'RUN_FRONTEND: running in watch mode'; npm run watch; else echo 'RUN_FRONTEND: running in prod mode'; tail -f /dev/null; fi"
directory=/code/ccm_web/client/src
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
startsecs=5
startretries=2
# Graceful stop, see http://nginx.org/en/docs/control.html
stopsignal=QUIT

[program:qworker]
command=bash -c ./shell_scripts/worker.sh
directory=/code
priority=20
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=DJANGO_SETTINGS_MODULE="backend.settings"