"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from django.core.management.utils import get_random_secret_key
from csp.constants import UNSAFE_INLINE, UNSAFE_EVAL
from backend.ccm.utils import parse_csp
from backend.ccm.canvas_scopes import DEFAULT_CANVAS_SCOPES
from datetime import timedelta
import json
import logging

config_to_bool = lambda value: str(value).lower() in ('true', '1', 'yes', 'on')

TEST_RUNNER = 'backend.tests.test_setup.CustomTestRunner'

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

PROJECT_ROOT = os.path.abspath(
    os.path.join(os.path.dirname(__file__), ".."),
)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', get_random_secret_key())

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config_to_bool(os.getenv('DEBUG', False))
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '').split(',')

# Application definition

INSTALLED_APPS = [
    'backend.ccm',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'webpack_loader',
    'watchman',
    'canvas_oauth.apps.CanvasOAuthConfig',
    'lti_tool',
    'rest_framework',
    'drf_spectacular',
    'rest_framework_tracking',
    'django_q',
    'csp',
]

MIGRATION_MODULES = {
    'canvas_oauth': 'backend.canvas_oauth.migrations',
    'rest_framework_tracking': 'backend.rest_framework_tracking.migrations',
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'servestatic.middleware.ServeStaticMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'lti_tool.middleware.LtiLaunchMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'canvas_oauth.middleware.OAuthMiddleware',
    'csp.middleware.CSPMiddleware'
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'backend.ccm.context_processors.ccm_globals'
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DB_NAME', 'ccm'),
        'USER': os.getenv('DB_USER', 'admin'),
        'PASSWORD': os.getenv('DB_PASSWORD', 'admin'),
        'HOST': os.getenv('DB_HOST', 'ccm_db'),
        'PORT': os.getenv('DB_PORT', '3306'),
        'OPTIONS': {'charset': 'utf8mb4'},
        'TEST': {
            'NAME': 'test_ccm',
            'CHARSET': 'utf8mb4',
            'COLLATION': 'utf8mb4_unicode_ci',
        }
    },
}

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": os.getenv('REDIS_LOCATION', "redis://ccm_redis:6379")
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = os.getenv('TIME_ZONE', os.getenv("TZ", "America/Detroit"))
USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'ccm_web'),
)
STATIC_ROOT = os.path.join(PROJECT_ROOT, 'static')

WEBPACK_LOADER = {
    'DEFAULT': {
        'BUNDLE_DIR_NAME': 'bundles/',
        'STATS_FILE': os.path.join(BASE_DIR, 'ccm_web/webpack-stats.json')
    }
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    # Gunicorns logging format https://github.com/benoitc/gunicorn/blob/19.x/gunicorn/glogging.py
    'formatters': {
        "generic": {
            "format": "%(asctime)s [%(levelname)s] [%(filename)s:%(lineno)d] %(message)s",
            "datefmt": "[%Y-%m-%d %H:%M:%S %z]",
            "class": "logging.Formatter",
        }
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'generic',
        },
    },
    'root': {
        'level': os.getenv('ROOT_LOG_LEVEL', 'INFO'),
        'handlers': ['console']
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'propagate': False,
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
        },
        'canvas_oauth': {
            'handlers': ['console'],
            'level': 'WARN'
        },
        'watchman': {
            'handlers': ['console'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
        }
    }
}

CONTENT_SECURITY_POLICY = {
    "DIRECTIVES": {
        "frame-ancestors": parse_csp('CSP_FRAME_ANCESTORS'),
        "script-src": parse_csp('CSP_SCRIPT_SRC', [UNSAFE_INLINE, UNSAFE_EVAL]),
        "connect-src": parse_csp('CSP_CONNECT_SRC'),
        "img-src": parse_csp('CSP_IMG_SRC'),
        "font-src": parse_csp('CSP_FONT_SRC'),
        "style-src": parse_csp('CSP_STYLE_SRC', ["https:", UNSAFE_INLINE]),
    }
}

# making LTI launch smooth
CSRF_COOKIE_SECURE = os.getenv("CSRF_COOKIE_SECURE", False)
if CSRF_COOKIE_SECURE:
    SESSION_COOKIE_SECURE = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    # Enables Proxies that set headers
    USE_X_FORWARDED_HOST = os.getenv('USE_X_FORWARDED_HOST', True)

SESSION_COOKIE_SAMESITE = os.getenv("SESSION_COOKIE_SAMESITE", 'None')
CSRF_COOKIE_SAMESITE = os.getenv("CSRF_COOKIE_SAMESITE", 'None')
RANDOM_PASSWORD_DEFAULT_LENGTH = os.getenv('RANDOM_PASSWORD_DEFAULT_LENGTH', 32)

# Google Analytics
GOOGLE_ANALYTICS_ID = os.getenv('GOOGLE_ANALYTICS_ID', None)
UM_CONSENT_MANAGER_SCRIPT_URL = os.getenv('UM_CONSENT_MANAGER_SCRIPT_URL', None)

HELP_URL = os.getenv('HELP_URL', 'https://ccm.tl-pages.tl.it.umich.edu')

# debugpy settings
DEBUGPY_ENABLE = config_to_bool(os.getenv('DEBUGPY_ENABLE', False))
DEBUGPY_REMOTE_ADDRESS = os.getenv('DEBUGPY_REMOTE_ADDRESS', '0.0.0.0')
DEBUGPY_REMOTE_PORT = os.getenv('DEBUGPY_REMOTE_PORT', 5678)
DEBUGPY_WAIT_FOR_DEBUGGER = config_to_bool(os.getenv('DEBUGPY_WAIT_FOR_DEBUGGER', False))

# Enable backend routes for local load testing. Defaults to False in production.
ENABLE_BACKEND = config_to_bool(os.getenv('ENABLE_BACKEND', False))

# Watchman settings (https://github.com/mwarkentin/django-watchman)
WATCHMAN_TOKENS = os.getenv('DJANGO_WATCHMAN_TOKENS', None)
WATCHMAN_TOKEN_NAME = os.getenv('DJANGO_WATCHMAN_TOKEN_NAME', 'ccm-watchman-token')
WATCHMAN_CHECKS = ('watchman.checks.caches', 'watchman.checks.databases')

# Canvas OAuth settings
CANVAS_OAUTH_CLIENT_ID = os.getenv('CANVAS_OAUTH_CLIENT_ID', '12342')
CANVAS_OAUTH_CLIENT_SECRET = os.getenv('CANVAS_OAUTH_CLIENT_SECRET', 'ccm')
CANVAS_OAUTH_CANVAS_DOMAIN = os.getenv('CANVAS_OAUTH_CANVAS_DOMAIN', 'canvas.test.instructure.com')
# Canvas OAuth token expiration buffer: refresh token 15 minutes before expiry by default
try:
    CANVAS_OAUTH_TOKEN_EXPIRATION_BUFFER = timedelta(minutes=int(os.getenv('CANVAS_OAUTH_TOKEN_EXPIRATION_BUFFER', 15)))
except Exception:
    CANVAS_OAUTH_TOKEN_EXPIRATION_BUFFER = timedelta(minutes=15)

# Scopes environment variable provides a way to recover if Canvas changes scope identifiers.
if isinstance((env_canvas_scopes := os.getenv('CANVAS_OAUTH_SCOPES')), str):
    CANVAS_OAUTH_SCOPES = env_canvas_scopes.split(',')
else:
    CANVAS_OAUTH_SCOPES = DEFAULT_CANVAS_SCOPES

REST_FRAMEWORK = {
    'EXCEPTION_HANDLER': 'backend.ccm.canvas_api.drf_custom_exception_handler.custom_exception_handler',
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Canvas Course Manager API',
    'DESCRIPTION': 'Canvas Course Admin features for U-M',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

DRF_TRACKING_ADMIN_LOG_READONLY = True

# https://django-q2.readthedocs.io/en/master/configure.html
Q_CLUSTER = {
    'name': 'CCM_Cluster',
    'workers': int(os.getenv('Q_CLUSTER_WORKERS', 4)),
    'timeout': int(os.getenv('Q_CLUSTER_TIMEOUT', 15 * 60)),  # 15 minutes in seconds
    'retry': int(os.getenv('Q_CLUSTER_RETRY', 30 * 60)),      # 30 minutes in seconds
    'bulk': int(os.getenv('Q_CLUSTER_BULK', 5)),
    'max_attempts': int(os.getenv('Q_CLUSTER_MAX_ATTEMPTS', 1)),
    'orm': 'default'
}

# Custom Canvas Roles
try:
    CUSTOM_CANVAS_ROLES = json.loads(os.getenv('CUSTOM_CANVAS_ROLES', '{"assistant": 34, "librarian": 21}'))
except Exception:
    CUSTOM_CANVAS_ROLES = {'assistant': 34, 'librarian': 21}

# Email settings
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'localhost')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = True

EMAIL_FROM = os.getenv('EMAIL_FROM', 'canvas-ccm-system@umich.edu')
EMAIL_TO_REPLY = os.getenv('EMAIL_TO_REPLY', '4help@umich.edu')
EMAIL_DEBUG = os.getenv('EMAIL_DEBUG', False)

CANVAS_ADMIN_API_TOKEN = os.environ.get('CANVAS_ADMIN_API_TOKEN')
if CANVAS_ADMIN_API_TOKEN is None or CANVAS_ADMIN_API_TOKEN == '':
    logging.error('CANVAS_ADMIN_API_TOKEN is not set in environment variables!')

GUEST_ACCOUNT_CREATION_LINK = os.getenv('GUEST_ACCOUNT_CREATION_LINK', 'https://accounts.it.umich.edu/friend/')
